command=~/.config/i3/bar/modules/$BLOCK_NAME
markup=pango
full_text=
align=center
color=#7780a1
separator=false
separator_block_width=4

[window_title]
command=~/.config/i3/bar/modules/window_title 45
interval=once
signal=11
color=#7780A1
align=left

[separator]

[ssid]
command=echo "$(iw dev wlan0 link | grep SSID | cut -d " " -f 2-)"
interval=300

[wifi]
command=~/.config/i3/bar/modules/wifi
instance=wlan0
label=
color=#7780a1
interval=300

[separator]

[battery]
command=~/.config/i3/bar/modules/battery
interval=60

[separator]

[disk]
command=df -h | grep /dev/sda5 | awk '{print "",$5,$4}'
interval=3600

[separator]

[temperature]
command=~/.config/i3/bar/modules/temperature -w 53 -c 65 --chip coretemp-isa-0000
label= 
interval=10

[separator]

[weather]
command=~/.config/i3/bar/modules/weather -c Mendoza
interval=10800
color=#C9CCDB

[separator]

[volume]
command=~/.config/i3/bar/modules/volume_pipewire
signal=10
interval=once

[separator]

[pacman]
command=~/.config/i3/bar/modules/pacman
label=📦
interval=10800

[separator]

[date]
command=echo "`date +'%d %b'`" ; [[ -z "${BLOCK_BUTTON}" ]] || st -g 62x22 -e calcurse &
interval=28800
color=#C9CCDB

[time]
command=echo " `date +'%H:%M'`"
interval=60
label=
color=#C9CCDB

[separator]

[bluetooth]
command=~/.config/i3/bar/modules/bluetooth
signal=11
interval=once

[separator]
