#!/usr/bin/bash

#PACKAGES=$(pacman -Qu | wc -l)
#counts lines and ignores lines with [ignored] packages
PACKAGES=$(checkupdates | grep -v -c ignored)
#PACKAGES=4
URGENT_VALUE=10
FULLICON=
SHORTICON=
OKCOLOR=#A8FF00
WARNCOLOR=#FFAE00
URGENTCOLOR=#FF0000

if [[ $PACKAGES -gt 0 && $PACKAGES -gt $URGENT_VALUE ]]; then
    echo '<span foreground="'$URGENTCOLOR'">'"$PACKAGES"'</span>' # full-text
    echo '<span foreground="'$URGENTCOLOR'">'"[$PACKAGES]"'</span>' # short-text
elif [[ $PACKAGES -gt 0 ]]; then
    echo '<span foreground="'$WARNCOLOR'">'"$PACKAGES"'</span>' # full-text
    echo '<span foreground="'$WARNCOLOR'">'"[$PACKAGES]"'</span>' # short-text
elif [[ $PACKAGES -eq 0 ]]; then
    echo '<span foreground="'$OKCOLOR'">'"$FULLICON"'</span>' #full-text
    echo '<span foreground="'$OKCOLOR'">'"$SHORTICON"'</span>' #short-text 
fi

#---------i3blocks actions-----------------------------------------------

case $BLOCK_BUTTON in
	2) pamac-manager ;; # middle click
	3) pamac-updater ;; # right click - opens pamac-updater
esac
