#!/usr/bin/env bash

set -e

PROGRAMS=(xfce4 ncmpcpp neofetch zprezto mpdnotify gtk-3.0 gtk-2.0 mpv mpd i3 fonts ranger htop zathura feh dunst calcurse picom rofi local_bin bash vim botp nano x11 tmux)

for program in ${PROGRAMS[@]}; do
  stow -t /home/poole/ --no-folding --verbose $program
  echo "Configuring $program"
done

echo "Done!"
