# Assigns & window behaviour
assign [class="(?i)(google-chrome|chromium|firefox|zen-alpha|zen-beta|zen|Navigator|Brave-origin)"] number $ws_1
assign [class="(?i)^(kitty|xfce4-terminal)$"] number $ws_2
assign [class="(?i)(nautilus|nemo|thunar)"] number $ws_3
assign [class="(?i)(subl|code-oss|.*zed.*)"] number $ws_4
for_window [class="(?i)(subl|sublime_*|code-oss|.*zed.*)"] layout stacked
assign [class="(?i)(brave-browser|Keepass)"] number $ws_5
for_window [class="Spotify"] move to workspace number $ws_5
assign [class="(?i)(libreoffice.*|gimp)"] number $ws_6
assign [class="(?i)(mpv|gpicview|zathura)"] number $ws_7
assign [class="(?i)(telegramdesktop|localsend)"] number $ws_9
assign [class="(?i)(virt-manager|rustdesk|protonvpn|obsidian)"] number $ws_10

default_border pixel 1
default_floating_border pixel 1
hide_edge_borders none
for_window [all] border pixel 1

for_window [window_role="(pop-up|task_dialog|bubble|dialog|menu|Preferences)"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_type="menu"] floating enable

for_window [class="(?i)(pavucontrol|qt5ct|gsimplecal|file-roller|whatsie|steam|mpv|virt-manager|seahorse|protonvpn|rustdesk|localsend)"] floating enable

for_window [class="(?i)firefox" window_role="pop-up"] floating enable
for_window [class="(?i)blueman-manager|Blueman-manager"] floating enable, resize set 600 680, move absolute position center
for_window [class="(?i)zen|Navigator"] layout tabbed
for_window [class="(?i)Navigator|zen" title="(?i)Comprobante"] focus

for_window [class="(?i)(sublime_text|subl|firefox|chrome|chromium|zen|Navigator|discord|zathura|gpicview|telegramdesktop)"] border none

for_window [class="(?i)qt5ct"] floating enable, border normal, resize set 600 680, move absolute position center
for_window [class="(?i)gsimplecal"] floating enable, move position mouse, move down 34 px
for_window [class="(?i)nemo-preview-start"] floating enable, border pixel 4, move absolute position center
for_window [title="Administracion - Remote Desktop - RustDesk"] floating disable, border 0, move center
for_window [class="steam"] floating enable, border none, resize set 960 640

for_window [class="drawn-st"] floating enable, border none
for_window [instance="bluetui-terminal"] floating enable, border normal, resize set 900 450, move absolute position center
for_window [instance="impala-terminal"] floating enable, border normal, resize set 900 450, move absolute position center
for_window [class="^st$" instance="^st$"] floating enable, border none
for_window [class="floating_update"] floating enable, border pixel 2
for_window [class="kitty-float"] floating enable, border pixel 2, resize set 900 550, move absolute position center
for_window [class="kitty-full"] floating enable, border none, fullscreen enable
for_window [class="kitty-scratch"] floating enable, border pixel 2, move scratchpad, scratchpad show, resize set 1000 600, move position center

for_window [class="(?i)pavucontrol"] move scratchpad
for_window [class="(?i)pidgin"] floating_maximum_size 50 x 75
for_window [window_role="(Open Document|task_dialog)"] floating_maximum_size 670 x 470
