# Binding modes
set $mode_resize resize: h j k l (+shift/ctrl)
mode "$mode_resize" {
  bindsym h resize shrink width  50 px or 5 ppt
  bindsym j resize grow   height 50 px or 5 ppt
  bindsym k resize shrink height 50 px or 5 ppt
  bindsym l resize grow   width  50 px or 5 ppt

  bindsym Shift+h resize shrink width  100 px or 10 ppt
  bindsym Shift+j resize grow   height 100 px or 10 ppt
  bindsym Shift+k resize shrink height 100 px or 10 ppt
  bindsym Shift+l resize grow   width  100 px or 10 ppt

  bindsym Control+h resize shrink width  200 px or 20 ppt
  bindsym Control+j resize grow   height 200 px or 20 ppt
  bindsym Control+k resize shrink height 200 px or 20 ppt
  bindsym Control+l resize grow   width  200 px or 20 ppt

  bindsym Shift+Control+h resize shrink width  300 px or 30 ppt
  bindsym Shift+Control+j resize grow   height 300 px or 30 ppt
  bindsym Shift+Control+k resize shrink height 300 px or 30 ppt
  bindsym Shift+Control+l resize grow   width  300 px or 30 ppt

  bindsym Left  resize shrink width  50 px or 5 ppt
  bindsym Down  resize grow   height 50 px or 5 ppt
  bindsym Up    resize shrink height 50 px or 5 ppt
  bindsym Right resize grow   width  50 px or 5 ppt

  bindsym Shift+Left  resize shrink width  100 px or 10 ppt
  bindsym Shift+Down  resize grow   height 100 px or 10 ppt
  bindsym Shift+Up    resize shrink height 100 px or 10 ppt
  bindsym Shift+Right resize grow   width  100 px or 10 ppt

  bindsym Control+Left  resize shrink width  200 px or 20 ppt
  bindsym Control+Down  resize grow   height 200 px or 20 ppt
  bindsym Control+Up    resize shrink height 200 px or 20 ppt
  bindsym Control+Right resize grow   width  200 px or 20 ppt

  bindsym Shift+Control+Left  resize shrink width  300 px or 30 ppt
  bindsym Shift+Control+Down  resize grow   height 300 px or 30 ppt
  bindsym Shift+Control+Up    resize shrink height 300 px or 30 ppt
  bindsym Shift+Control+Right resize grow   width  300 px or 30 ppt

  bindsym Return mode "default"
  bindsym Escape mode "default"
}
bindsym $mod+r mode "$mode_resize"

set $mode_gaps Gaps: (o) outer, (i) inner
set $mode_gaps_outer Outer Gaps: +(8)|-(9)|0 (local), +(6)|-(7)|0(5) (global)
set $mode_gaps_inner Inner Gaps: +(8)|-(9)|0 (local), +(6)|-(7)|0(5) (global)

bindsym $mod+Shift+g mode "$mode_gaps"
mode "$mode_gaps" {
    bindsym o      mode "$mode_gaps_outer"
    bindsym i      mode "$mode_gaps_inner"
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

mode "$mode_gaps_inner" {
    bindsym 8    gaps inner current plus 5
    bindsym 9    gaps inner current minus 5
    bindsym 0    gaps inner current set 0
    bindsym 6    gaps inner all plus 5
    bindsym 7    gaps inner all minus 5
    bindsym 5    gaps inner all set 0
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

mode "$mode_gaps_outer" {
    bindsym 8     gaps outer current plus 5
    bindsym 9     gaps outer current minus 5
    bindsym 0     gaps outer current set 0
    bindsym 6     gaps outer all plus 5
    bindsym 7     gaps outer all minus 5
    bindsym 5     gaps outer all set 0
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

mode "focused" {
  bindsym b [class="(?i)zen|Navigator"] focus
  bindsym w [class="(?i)kitty"] focus
  bindsym m [class="(?i)nemo"] focus
  bindsym z [class="(?i)zathura"] focus
  bindsym c [class="(?i)code-oss|code"] focus

  bindsym a exec i3-input -F 'mark %s' -P 'Mark name: '
  bindsym g exec i3-input -F '[con_mark=%s] focus' -P 'Go to mark: '

  bindsym Shift+1 mark mark1
  bindsym Shift+2 mark mark2
  bindsym Shift+3 mark mark3
  bindsym Shift+4 mark mark4
  bindsym Shift+5 mark mark5

  bindsym 1 [con_mark="mark1"] focus
  bindsym 2 [con_mark="mark2"] focus
  bindsym 3 [con_mark="mark3"] focus
  bindsym 4 [con_mark="mark4"] focus
  bindsym 5 [con_mark="mark5"] focus

  bindsym Return mode "default"
  bindsym Escape mode "default"
}
