# Appearance
set $base00 #101218
set $base01 #1f222d
set $base02 #252936
set $base03 #7780a1
set $base04 #ffffff
set $base05 #d1d4e0
set $base06 #FF1B6D
set $base07 #1f222d

font pango: Iosevka Nerd Font Mono, FontAwesome 12

# Roomier gaps on terminal (ws2) and free/spacious workspace (ws8)
workspace $ws_2 gaps inner 15
workspace $ws_2 gaps outer 0
workspace $ws_8 gaps inner 15
workspace $ws_8 gaps outer 0

gaps inner 3
gaps outer 1
smart_gaps on
smart_borders on

#                         border  background text    indicator
client.focused            $base01 $base01    $base04 $base07
client.focused_inactive   $base02 $base02    $base03 $base07
client.unfocused          $base02 $base02    $base03 $base07
client.urgent             $base02 $base06    $base00 $base07
