# Status bar
bar {
    status_command i3blocks -c ~/.config/i3/bar/myblocks.conf
    i3bar_command i3bar -t
    verbose no
    id bar-1
    height 24
    tray_padding 0
    strip_workspace_numbers yes
    font pango: tewi, FontAwesome 8
    position top
    colors {
        separator  $base03
        background $base01
        statusline $base05
        #                          border  background text
        focused_workspace  $base01 $base01    $base04
        active_workspace   $base01 $base02    $base03
        inactive_workspace $base01 $base01    $base03
        urgent_workspace   $base01 $base01    $base06
    }
}
