export PATH=$HOME/bin:/usr/local/bin:$PATH

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

if [ -f /etc/bash_completion.d/climate_completion ]; then
	source /etc/bash_completion.d/climate_completion
fi

#source /etc/bash_completion.d/climate_completion


#-------- External Files {{{
#------------------------------------------------------

# load alias/functions that works with both zsh/bash
if [[ -f ~/.aliasrc ]]; then
    source ~/.aliasrc
fi


#if zplug check zsh-users/zsh-history-substring-search; then
#    bindkey '^[[A' history-substring-search-up
#    bindkey '^[[B' history-substring-search-down
#fi

#zplug load

#bindkey "^[OA" history-substring-search-up
#bindkey "^[OB" history-substring-search-down
eval $(thefuck --alias)
